services:
  api:
    build: .
    command: poetry run uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src

  streamlit:
    build: .
    command: poetry run streamlit run src/app.py --server.address 0.0.0.0 --server.port 8501 --server.enableCORS false
    ports:
      - "8502:8501"
    volumes:
      - .:/app
    working_dir: /app

  mlflow:
    image: ghcr.io/mlflow/mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
      - GIT_PYTHON_REFRESH=quiet
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --backend-store-uri /mlflow/mlruns --host 0.0.0.0